### ISSUE TITLE
fails to npm install on latest Raspbian Buster Lite

### ISSUE THREAD

**Issue by cipy** [mimeindustries/mearm-js#9]
> make: Leaving directory '/home/pi/work/mearm-js/node_modules/pigpio/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.19.97-v7+
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd /home/pi/work/mearm-js/node_modules/pigpio
> gyp ERR! node -v v10.15.2
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: i2c-bus@1.1.2 (node_modules/i2c-bus):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: i2c-bus@1.1.2 install: `node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.3.2 (node_modules/pigpio):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.3.2 install: `node-gyp rebuild`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
>

**Comment by cipy** [comment]
still fails, even with the latest update of the README

> gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/work/mearm-js/node_modules/pigpio
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: i2c-bus@1.1.2 (node_modules/i2c-bus):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: i2c-bus@1.1.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.3.2 (node_modules/pigpio):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.3.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by cipy** [comment]
sudo nodejs ./server.js
> { Error: Cannot find module 'pigpio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/work/mearm-js/lib/Servo.js:1:74)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }

**Comment by cipy** [comment]
Oh, it looks like your (npm) deps are too old and won't compile.

This will fix them, and make everything work:

>   "dependencies": {
    "wireless-tools": "git+https://git@github.com/headlessPi/wireless-tools.git",
    "ws": "^7.2.1"
  },
  "optionalDependencies": {
    "i2c-bus": "^5.1.0",
    "pigpio": "^3.0.0"
  },

**Comment by sanniu123** [comment]
Hi, have you fixed the issue? Could you elaborate how to fix it? I have limited experience with Raspberry Pi. Thx.

**Comment by cipy** [comment]
@sanniu123 you'd need to edit your _package.json_ file to look as above ⬆️ 

then run $ `npm install`

**Comment by sanniu123** [comment]
Thanks. It works for me.

**Comment by verschneidert** [comment]
@cipy by "edit" you mean replace with the above or add the above?

**Comment by cipy** [comment]
Replace

**Comment by verschneidert** [comment]
thanks a lot. works now :)
